version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run: pip install pybuilder --pre pybuilder
      - run: pyb clean
      - run: pyb -v


workflows:
  main:
    jobs:
      - build-and-test
